project:
  type: website
  output-dir: .

website:
  title: "Charles' Website"
  navbar:
    left:
      - text: About You
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd
format:
  html:
    theme: cosmo
    css: styles.css